name: Build and Push Vue or Spring Boot Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_gost:
        description: 'Build GOST binary'
        required: false
        type: boolean
        default: false
      build_vite:
        description: 'Build Vite frontend'
        required: false
        type: boolean
        default: false
      build_java:
        description: 'Build Spring Boot backend'
        required: false
        type: boolean
        default: false

jobs:
  build-gost:
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.build_gost == 'true')
    name: Build & Compress GOST Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz
          tar -xf upx-4.2.1-amd64_linux.tar.xz
          sudo mv upx-4.2.1-amd64_linux/upx /usr/local/bin/
          rm -rf upx-4.2.1-amd64_linux*

      - name: Build GOST binary
        working-directory: ./go-gost
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o gost

      - name: Compress with UPX
        working-directory: ./go-gost
        run: |
          upx --best --lzma gost

      - name: Create or Update Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 确保 tag 指向当前 commit
          git tag -f gost-latest ${{ github.sha }}
          git push origin gost-latest --force

          # 检查 release 是否存在，不存在则创建
          if gh release view gost-latest 2>/dev/null; then
            echo "Release exists, will update assets"
          else
            echo "Release not found, creating new release"
            gh release create gost-latest gost-latest \
              --title "GOST Binary Latest" \
              --notes "GOST binary compiled from commit ${{ github.sha }}
          
          - Platform: Linux AMD64
          - Compressed with UPX
          - Build date: ${{ github.event.head_commit.timestamp }}" \
              --repo ${{ github.repository }}
          fi

          # 上传 asset 并覆盖同名文件
          gh release upload gost-latest ./go-gost/gost --clobber


  build-vite:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.build_vite == 'true')
    name: Build & Push Vite Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Vite multi-arch image
        run: |
          echo "Building and pushing xydgg/vite-frontend:latest"
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t xydgg/vite-frontend:latest \
            ./vite-frontend
          echo "Build completed, checking if image was pushed..."
          docker buildx imagetools inspect xydgg/vite-frontend:latest

  build-java:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.build_java == 'true')
    name: Build & Push Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Java JAR
        working-directory: ./springboot-backend
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Java multi-arch image
        run: |
          echo "Building and pushing xydgg/springboot-backend:latest"
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t xydgg/springboot-backend:latest \
            ./springboot-backend
          echo "Build completed, checking if image was pushed..."
          docker buildx imagetools inspect xydgg/springboot-backend:latest
